substitutions:
  name: "m5-dial"
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password  

packages:
  m5_tough_package:
    url: https://github.com/jandahl/m5-dial-for-esphome
    ref: main
    file: shys-m5-dial.yaml
    refresh: 1h

shys_m5_dial:
  name: Dial
  screen_off_time: 45000
  rotary_step_width: 5
  long_press_duration: 1200
  font: FreeSans14pt7b
  font_factor: 1

  devices:
    media_player:
      - entity: media_player.bedroom_spy
        name: "Bedroom spy"
        modes:
          play_mode:
            rotary_step_width: 10
          source_mode:
            rotary_step_width: 1
            sources:
              - name: "P4 Sjaelland"
                content_id: "https://drliveradio1.akamaized.net/hls/live/2097651/p4sjaelland/masterab.m3u8"
                content_type: TUNEIN
              - name: "KNR"
                content_id: "http://knr.gl/radiolivestream"
                content_type: TUNEIN
    
    climates:
      - entity: climate.bedroom # .temperature
        name: "Bedroom temperature"
        modes:
          temp_mode:
            rotary_step_width: 1
            min_temperature: 15
            max_temperature: 25

    lights: 
      - entity: light.jan_bedroom_lamp
        name: "Jan bedroom lamp"
        modes:
          dimm_mode:
            enable: true
            rotary_step_width: 10
          rgb_mode:
            enable: false
          white_mode:
            enable: true
            rotary_step_width: 10
            min_kelvin: 2500
            max_kelvin: 7000 
      - entity: light.walk_in_closet
        name: "Walk-in closet"
        modes:
          dimm_mode:
            enable: true
            rotary_step_width: 10
          rgb_mode:
            enable: true
            rotary_step_width: 30
